version: "3.3"
services:
  web:
    build: ./frontend
#    image: honeywell/assetmanagement-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./backend
#    image: honeywell/assetmanagement-backend
    ports:
      - "8090:80"
    